name: Integration tests

on:
  pull_request:
  workflow_dispatch:
  inputs:
    url:
      description: 'API URL to test'
      required: true

env:
  CI: true
  WALLET_ENVIRONMENT: testing

jobs:
  test-desktop:
    runs-on: ubuntu-latest
    env:
      STX_NETWORK: testnet
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
    steps:
      - name: Clone supercharge docs repository
        uses: actions/checkout@v2
        with:
          repository: hirosystems/stacks-wallet
          path: stacks-desktop-wallet/

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: sudo apt-get update

      - run: sudo apt-get install libusb-1.0-0-dev libudev-dev

      - name: Install packages
        uses: nick-invision/retry@v2
        with:
          timeout_seconds: 600
          max_attempts: 5
          retry_on: error
          command: cd ./stacks-desktop-wallet && yarn --frozen-lockfile

      - uses: microsoft/playwright-github-action@v1

      - name: Install electron-prebuilt
        uses: nick-invision/retry@v2
        with:
          timeout_seconds: 300
          max_attempts: 5
          retry_on: error
          command: cd ./stacks-desktop-wallet && yarn add electron-prebuilt --ignore-scripts

      - run: cd ./stacks-desktop-wallet/node_modules/electron && sudo node install.js

      - name: Build assets
        run: ./node_modules/.bin/cross-env yarn build
        working-directory: ./stacks-desktop-wallet
        env:
          NODE_ENV: production
          SHA: ${{ github.event.pull_request.head.sha }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: xvfb-run --auto-servernum -- yarn test:integration
        working-directory: ./stacks-desktop-wallet

  directories:
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.set-dirs.outputs.dir }}
    steps:
      - uses: actions/checkout@v2
      - id: set-dirs
        working-directory: ./tests/integration
        run: echo "::set-output name=dir::$( ls -d */ | xargs -0 | sed 's/\///' | jq -R -s -c 'split("\n")[:-2]')"

  test-integration:
    runs-on: ubuntu-latest
    needs: [directories]
    strategy:
      matrix:
        dir: ${{ fromJson(needs.directories.outputs.dir) }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - run: echo ${{ fromJson(needs.directories.outputs.dir) }}
      - run: echo ${{ matrix.dir }}

      - uses: actions/cache@v2
        name: Cache node_modules
        id: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/package.json') }}

      - uses: actions/cache@v2
        name: Cache playwright
        id: cache-playwright-browsers
        with:
          path: '~/.cache/ms-playwright'
          key: ${{ runner.os }}-playwright-browser

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install packages
        uses: ./.github/actions/provision
        if: steps.cache-node-modules.outputs.cache-hit != 'true'

      - name: Install Playwright dependencies
        run: npx playwright install

      - name: Build assets
        run: yarn build:test

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Run tests
        run: |
          xvfb-run --auto-servernum -- \
            yarn jest \
              --config=./jest.integration.config.js \
              --detectOpenHandles \
              --forceExit \
              --testPathPattern=./tests/integration/${{ matrix.dir }}/*

      - name: Upload traces
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: traces-${{ matrix.dir }}-${{ steps.date.outputs.date }}
          path: '**/**.trace.zip'
